<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="/entry" method="post">
        <input type="text" name="title" placeholder="Title">
        <input type="text" name="text">
        <input type="date" name="date">
        <input type="text" name="location" placeholder="Location">
        <input type="checkbox" name="isPrivate">
        <input type="submit" value="Save">
    </form>

</body>
</html>