<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up</title>
</head>
<body>
    <form action="/signUp" method="post">
        <input name="firstName" placeholder="First Name">
        <input name="lastName" placeholder="Last Name">
        <input name="username" id="Username">
        <input type="email" name="email" placeholder="Email">
        <input type="password" name="password" placeholder="Пароль">
        <input type="submit" value="Sign Up">
    </form>
</body>
</html>